# Generated by Django 4.0.1 on 2022-01-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.IntegerField()),
                ('division', models.CharField(max_length=1, verbose_name='division')),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='año_nacimiento',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
