# Generated by Django 3.1.2 on 2022-01-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20220119_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docentes',
            old_name='telefono',
            new_name='telefono_contacto',
        ),
    ]
